postgresql:
  image: postgres:9.3
  ports:
    - "5432:5432"
  volumes:
    - .docker/postgres:/var/lib/postgresql/data
  environment:
    - POSTGRES_USER=sigmah
    - POSTGRES_PASSWORD=sigmah
    - POSTGRES_DB=sigmah
   